### ISSUE TITLE
On some device ‘pause()’ and 'cancel()' may lead force quit

### ISSUE THREAD

**Issue by Aspsine** [Aspsine/MultiThreadDownload#25]
#23 

08-31 21:10:45.594    8700-8700/com.aspsine.multithreaddownload E/Parcel﹕ Reading a NULL string not supported here.
08-31 21:11:52.984    8700-8700/com.aspsine.multithreaddownload E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.aspsine.multithreaddownload, PID: 8700
    android.os.NetworkOnMainThreadException
            at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1145)
            at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:163)
            at libcore.io.IoBridge.recvfrom(IoBridge.java:506)
            at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
            at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
            at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240)
            at java.io.BufferedInputStream.read(BufferedInputStream.java:283)
            at com.android.okhttp.internal.http.HttpTransport$FixedLengthInputStream.read(HttpTransport.java:394)
            at com.android.okhttp.internal.Util.skipByReading(Util.java:274)
            at com.android.okhttp.internal.http.HttpTransport.discardStream(HttpTransport.java:195)
            at com.android.okhttp.internal.http.HttpTransport.access$200(HttpTransport.java:32)
            at com.android.okhttp.internal.http.HttpTransport$FixedLengthInputStream.close(HttpTransport.java:416)
            at com.android.okhttp.internal.Util.closeQuietly(Util.java:110)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.disconnect(HttpURLConnectionImpl.java:102)
            at com.aspsine.multithreaddownload.core.AbsDownloadTask.pause(AbsDownloadTask.java:69)
            at com.aspsine.multithreaddownload.core.DownloadRequest.pause(DownloadRequest.java:148)
            at com.aspsine.multithreaddownload.DownloadManager.pause(DownloadManager.java:136)
            at com.aspsine.multithreaddownload.demo.ui.fragment.ListViewFragment.onItemClick(ListViewFragment.java:88)
            at com.aspsine.multithreaddownload.demo.ui.fragment.ListViewFragment.onItemClick(ListViewFragment.java:33)
            at com.aspsine.multithreaddownload.demo.ui.adapter.ListViewAdapter$1.onClick(ListViewAdapter.java:83)
            at android.view.View.performClick(View.java:4635)
            at android.view.View$PerformClick.run(View.java:19163)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5117)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by Aspsine** [comment]
some hint:
http://techblog.bozho.net/caveats-of-httpurlconnection/

**Comment by lacorey** [comment]
现在修复这个问题了吗？

**Comment by Aspsine** [comment]
@lacorey 
No. It haven't fixed yet.
I am focusing on the another lib these days. 
So sorry for the delay.

**Comment by Aspsine** [comment]
some hint:
https://android.googlesource.com/platform/packages/providers/DownloadProvider/+/master

**Comment by utfqvfhpyygy** [comment]
这个问题好处理吗？

**Comment by utfqvfhpyygy** [comment]
@Aspsine  这个问题最近能修复吗

**Comment by BrightYu** [comment]
同样发现了这个问题

**Comment by Aspsine** [comment]
@lacorey  @utfqvfhpyygy  @BrightYu 

thanks guys.

I fixed this issue in this fork:
https://github.com/Aspsine/MultiThreadDownload/tree/thunder

It is not a released lib and not full tested.

**Comment by whisper90** [comment]
打扰，简单看了一下，您这个下载不是通过service的方式实现的吗

**Comment by Aspsine** [comment]
@whisper90 
Service 中的使用，请参考：
https://github.com/Aspsine/MultiThreadDownload/blob/thunder/app/src/main/java/com/aspsine/multithreaddownload/demo/service/DownloadService.java

**Comment by whisper90** [comment]
@Aspsine 3ks
