### ISSUE TITLE
Demo运行报错

### ISSUE THREAD

**Issue by ZhaoKaiQiang** [Aspsine/MultiThreadDownload#33]
点击开始，然后暂停，报错，Demo是在主线程操作网络？这么明显的BUG不应该存在吧

 FATAL EXCEPTION: main
                                                                               Process: com.aspsine.multithreaddownload, PID: 8877
                                                                               android.os.NetworkOnMainThreadException
                                                                                   at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1145)
                                                                                   at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:163)
                                                                                   at libcore.io.IoBridge.recvfrom(IoBridge.java:506)
                                                                                   at java.net.PlainSocketImpl.read(PlainSocketImpl.java:489)
                                                                                   at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
                                                                                   at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:241)
                                                                                   at java.io.BufferedInputStream.read(BufferedInputStream.java:283)
                                                                                   at com.android.okhttp.internal.http.HttpTransport$FixedLengthInputStream.read(HttpTransport.java:386)
                                                                                   at libcore.io.Streams.skipByReading(Streams.java:158)
                                                                                   at java.io.InputStream.skip(InputStream.java:227)
                                                                                   at com.android.okhttp.internal.Util.skipAll(Util.java:249)
                                                                                   at com.android.okhttp.internal.http.HttpTransport.discardStream(HttpTransport.java:190)
                                                                                   at com.android.okhttp.internal.http.HttpTransport.access$200(HttpTransport.java:32)
                                                                                   at com.android.okhttp.internal.http.HttpTransport$FixedLengthInputStream.close(HttpTransport.java:408)
                                                                                   at com.android.okhttp.internal.Util.closeQuietly(Util.java:110)
                                                                                   at com.android.okhttp.internal.http.HttpURLConnectionImpl.disconnect(HttpURLConnectionImpl.java:102)
                                                                                   at com.aspsine.multithreaddownload.core.AbsDownloadTask.pause(AbsDownloadTask.java:69)
                                                                                   at com.aspsine.multithreaddownload.core.DownloadRequest.pause(DownloadRequest.java:148)
                                                                                   at com.aspsine.multithreaddownload.DownloadManager.pause(DownloadManager.java:136)
                                                                                   at com.aspsine.multithreaddownload.demo.ui.fragment.ListViewFragment.onItemClick(ListViewFragment.java:88)
                                                                                   at com.aspsine.multithreaddownload.demo.ui.fragment.ListViewFragment.onItemClick(ListViewFragment.java:33)
                                                                                   at com.aspsine.multithreaddownload.demo.ui.adapter.ListViewAdapter$1.onClick(ListViewAdapter.java:83)
                                                                                   at android.view.View.performClick(View.java:4456)
                                                                                   at android.view.View$PerformClick.run(View.java:18490)
                                                                                   at android.os.Handler.handleCallback(Handler.java:733)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                   at android.os.Looper.loop(Looper.java:136)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5094)
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702)
                                                                                   at dalvik.system.NativeStart.main(Native Method)

**Comment by Aspsine** [comment]
#25
